version: "3"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=short_url_db
      - POSTGRES_USER=short_url_user
      - POSTGRES_PASSWORD=short_url_password
    ports:
      - 5432:5432
    volumes:
      - short_url-data:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

#  nginx:
#    image: nginx:latest
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#      - short_url-static:/staticfiles
#    depends_on:
#      - web
#
#  web:
#    build: ../../.
#    image: short_url
#    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --workers=2 --timeout 100 core.wsgi -b 0.0.0.0:8000 --reload"
#    volumes:
#      - short_url-static:/short_url/staticfiles
#    ports:
#      - 8000:8000
#    depends_on:
#      - redis

volumes:
  short_url-data:
  short_url-static: