version: "3"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  pgdata: