global:
    scrape_interval: 5s
    external_labels:
        monitor: 'demo-monitor'

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
    - job_name: 'api_monitor'
      scrape_interval: 5s
      static_configs:
        - targets: ['web:5000']