# Generated by Django 2.2.9 on 2021-03-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
