version: "3"

services:
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_DBNAME=postgisdbname
      - POSTGRES_USER=postgisuser
      - POSTGRES_PASSWORD=postgispassword
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: