# Generated by Django 2.2.9 on 2021-03-24 03:14

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', core.models.AutoPubIDField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='public_id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('message', models.CharField(max_length=256, verbose_name='message')),
                ('create_time', models.DateTimeField(verbose_name='create_time')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.Chat')),
            ],
        ),
    ]
