# Generated by Django 2.2.1 on 2019-06-12 03:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('pub_id', core.models.AutoPubIDField(blank=True, editable=False, max_length=20, unique=True, verbose_name='public id')),
                ('api_token', models.CharField(max_length=255, null=True, unique=True, verbose_name='api token')),
                ('sign_pub_key', models.CharField(max_length=255, unique=True, verbose_name='verify key')),
                ('name', models.CharField(max_length=128, verbose_name='name of app user')),
            ],
            options={
                'verbose_name': 'app_user',
                'verbose_name_plural': 'app_users',
            },
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'my_user', 'verbose_name_plural': 'my_users'},
        ),
    ]
