version: "3"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=djangosessionredisdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
    volumes:
      - sessionpgdata:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

volumes:
  sessionpgdata: